name: 'Test linter and formatting' 

on: 
  push: 
    branches: 
      - '*' 
      - '!master' 
      - '!develop' 

jobs: 
  test: 
    name: 'flake8 and black formatting' 
    runs-on: ubuntu-latest 

    steps: 
    - name: 'Checkout' 
      uses: actions/checkout@v2 

    - name: 'Test with tox'
      run: tox 
